branches:
  only:
  - source
language: ruby
rvm:
- 1.9.3
before_script:
- openssl aes-256-cbc -K $encrypted_853174b23cf4_key -iv $encrypted_853174b23cf4_iv -in id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- cp .ssh_config ~/.ssh/config
- git pull $REPO.git _deploy
script:
- rake generate
after_script:
- rake deploy
env:
  global:
  - REPO="git@github.com:tpluscode/tpluscode.github.io"
